name : Hello World
on:
 push:
  branches :
     - main
jobs :
    First-hello-world-job:
     runs-on : ubuntu-latest
     steps:
       - name: Checkout Code
         uses: actions/checkout@v3
       - name: print message
         run: echo "Hello world GA testing"
